#default_language_version:
#    python: python3.11
fail_fast: true

repos:
    # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 25.1.0
      hooks:
          - id: black
            # It is recommended to specify the latest version of Python
            # supported by your project here, or alternatively use
            # pre-commit's default_language_version, see
            # https://pre-commit.com/#top_level-default_language_version
            language_version: python3.13
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v5.0.0
        hooks:
        -   id: end-of-file-fixer
            files: ^.idea/
        -   id: trailing-whitespace
            exclude: ^site/
        -   id: check-executables-have-shebangs
        -   id: check-json
        -   id: check-toml
        -   id: check-yaml
            args: ['--unsafe']
        -   id: detect-private-key
        -   id: detect-aws-credentials
            args: ['--allow-missing-credentials']
        -   id: check-docstring-first
        -   id: mixed-line-ending
            args: ['--fix=auto']
        -   id: name-tests-test
            exclude: data.py
        -   id: pretty-format-json
            args: ['--autofix']
        -   id: check-merge-conflict
        -   id: debug-statements
        -   id: no-commit-to-branch
            # Both master and main are protected by default. Merge requests only.
        -   id: check-case-conflict
        -   id: check-byte-order-marker
    -   repo: https://github.com/asottile/add-trailing-comma
        rev: v3.1.0
        hooks:
        -   id: add-trailing-comma
            args: [--py35-plus]
    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
      - id: codespell
        args:
            - -w
        additional_dependencies:
          - tomli
        exclude: '^.idea|^.venv|^.site'
        exclude_types: [javascript]
    - repo: https://github.com/shssoichiro/oxipng
      rev: v9.1.4
      hooks:
      - id: oxipng
        args: [ "-o", "max", "--strip", "safe", "--alpha", "--preserve", "--recursive"]
exclude: '(site|.venv|.idea|.github|.pytest_cache)/.*'
